apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-0
  namespace: pgsql01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: repmgr
      node: pg-0
  template:
    metadata:
      labels:
        app: postgres
        role: repmgr
        node: pg-0
    spec:
      containers:
        - name: postgres
          image: postgres:16.2
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_USERNAME
              value: myuser
            - name: POSTGRESQL_PASSWORD
              value: mypassword
            - name: POSTGRESQL_DATABASE
              value: mydatabase
            - name: PG_MODE
              value: primary
          volumeMounts:
            - name: pg-data-0
              mountPath: /var/lib/postgresql
      volumes:
        - name: pg-data-0
          persistentVolumeClaim:
            claimName: postgres-storage-pvc-master-0
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: pgsql01
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-storage-master
  namespace: pgsql01
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /nfs/home/data/database/pg-sql-01/master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-pvc-master-0
  namespace: pgsql01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeName: postgres-storage-master

