apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-master-pv
  namespace: pg-sql-01
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: master
  hostPath:
    path: /nfs/home/data/database/pg-sql-01/pv-pos-master

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: pg-sql-01
spec:
  serviceName: postgres-deploy
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mydatabase01
            - name: POSTGRES_USER
              value: myuserpg01
            - name: POSTGRES_PASSWORD
              value: mypassword
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: postgres-master-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-master-pvc
  namespace: pg-sql-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: master

