apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-0
  namespace: pg-sql-01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
      role: repmgr
      node: pg-0
  template:
    metadata:
      labels:
        app: postgres
        role: repmgr
        node: pg-0
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql-repmgr:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_POSTGRES_PASSWORD
              value: adminpassword
            - name: POSTGRESQL_USERNAME
              value: myuser
            - name: POSTGRESQL_PASSWORD
              value: mypassword
            - name: POSTGRESQL_DATABASE
              value: mydatabase
            - name: POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS
              value: "1"
            - name: REPMGR_PRIMARY_HOST
              value: pg-0-0
            - name: REPMGR_PARTNER_NODES
              value: pg-0-0,pg-0-1
            - name: REPMGR_NODE_NAME
              value: pg-0-0
            - name: REPMGR_NODE_NETWORK_NAME
              value: pg-0-0
            - name: REPMGR_USERNAME
              value: repmgr
            - name: REPMGR_PASSWORD
              value: repmgrpassword
          volumeMounts:
            - name: pg-0-data
              mountPath: /bitnami/postgresql
            - name: pg-1-data
              mountPath: /bitnami/postgresql
      volumes:
        - name: pg-0-data
          persistentVolumeClaim:
            claimName: postgres-storage-pvc
        - name: pg-1-data
          persistentVolumeClaim:
            claimName: postgres-storage-svlave-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: pg-sql-01
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
