apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg
  namespace: pg-sql-01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  serviceName: pg
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql-repmgr:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_POSTGRES_PASSWORD
              value: adminpassword
            - name: POSTGRESQL_USERNAME
              value: myuser
            - name: POSTGRESQL_PASSWORD
              value: mypassword
            - name: POSTGRESQL_DATABASE
              value: mydatabase
            - name: POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS
              value: "1"
            - name: REPMGR_PRIMARY_HOST
              value: pg-0
            - name: REPMGR_PARTNER_NODES
              value: pg-0,pg-1
            - name: REPMGR_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REPMGR_NODE_NETWORK_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: REPMGR_USERNAME
              value: repmgr
            - name: REPMGR_PASSWORD
              value: repmgrpassword
          volumeMounts:
            - name: pg-data-0
              mountPath: /bitnami/postgresql/data
      volumes:
        - name: pg-data-0
          persistentVolumeClaim:
            claimName: postgres-storage-pvc-0
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: pg-sql-01
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
