apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-1
  namespace: pgsql01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: repmgr
      node: pg-1
  template:
    metadata:
      labels:
        app: postgres
        role: repmgr
        node: pg-1
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql-repmgr:14
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - PGPASSWORD=mypassword psql -U "myuser" -d "mydatabase" -h 127.0.0.1 -p 5432 -c "SELECT 1"
                - repmgr standby register
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_POSTGRES_PASSWORD
              value: adminpassword
            - name: POSTGRESQL_USERNAME
              value: myuser
            - name: POSTGRESQL_PASSWORD
              value: mypassword
            - name: POSTGRESQL_DATABASE
              value: mydatabase
            - name: POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS
              value: "1"
            - name: REPMGR_PRIMARY_HOST
              value: pgsql101.postgres-service.svc.cluster.local
            - name: REPMGR_PARTNER_NODES
              value: pg-1-0,pgsql101.postgres-service.svc.cluster.local
            - name: REPMGR_NODE_NETWORK_NAME
              value: pg-1-0
            - name: REPMGR_USERNAME
              value: repmgr
            - name: REPMGR_PASSWORD
              value: repmgrpassword
            - name: REPMGR_STANDBY_MODE
              value: "true"
          volumeMounts:
            - name: pg-1-data
              mountPath: /bitnami/postgresql
      volumes:
        - name: pg-1-data
          persistentVolumeClaim:
            claimName: postgres-storage-pvc-slave-0
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service-slave
  namespace: pgsql01
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-storage-slave-pv
  namespace: pgsql01
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /nfs/home/data/database/pg-sql-01/slave
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-pvc-slave-0
  namespace: pgsql01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeName: postgres-storage-slave-pv
