apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: pg-sql-01
spec:
  serviceName: postgres-statefulset
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage-01
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: mydatabase
            - name: POSTGRES_USER
              value: myuser01
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRESQL_PGAUDIT_LOG
              value: 'READ,WRITE'
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage-02
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: mydatabase
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRESQL_PGAUDIT_LOG
              value: 'READ'
      volumes:
        - name: postgres-storage-01
          persistentVolumeClaim:
            claimName: postgres-pvc-01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-01
  namespace: pg-sql-01
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /nfs/home/data/database/pg-sql-01/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-01
  namespace: pg-sql-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual