apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-slave-pv
  namespace: pg-sql-01
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: master
  hostPath:
    path: /nfs/home/data/database/pg-sql-01/pv-pos-slave

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-slave
  labels:
    app: postgres
spec:
  replicas: 2
  serviceName: postgres-master
  selector:
    matchLabels:
      app: postgres
      role: slave
  template:
    metadata:
      labels:
        app: postgres
        role: slave
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: mydatabase
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-slave-pvc
  namespace: pg-sql-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: master

