apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: pg-sql-01
spec:
  serviceName: postgres-deploy
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mydatabase01
            - name: POSTGRES_USER
              value: myuser01
            - name: POSTGRES_PASSWORD
              value: mypassword
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
        namespace: pg-sql-01
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-master-pv
  namespace: pg-sql-01
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /nfs/home/data/database/pg-sql-01/master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-master-pvc
  namespace: pg-sql-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: postgres-master-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-slave-pv
  namespace: pg-sql-01
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /nfs/home/data/database/pg-sql-01/slave
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-slave-pvc
  namespace: pg-sql-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: postgres-slave-pv