apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-master-pv
  labels:
    type: local   
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  local:
    path: /nfs/home/data/database/pg-sql-01/master
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
              - postgres
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-slave-pv
  labels:
    type: local   
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  local:
    path: /nfs/home/data/database/pg-sql-01/slave
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
              - postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-master-pvc
  namespace: pg-sql-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: postgres-master-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-slave-pvc
  namespace: pg-sql-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: postgres-slave-pv
