# Slave
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-slave-02
  namespace: postgres-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-slave-02
  template:
    metadata:
      labels:
        app: postgres-slave-02
    spec:
      containers:
        - name: postgres-slave-02
          image: bitnami/postgresql:16
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "2Gi"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRESQL_PASSWORD
            value: "postgres"
          - name: POSTGRESQL_MASTER_HOST
            value: "postgres-master-svc-02.postgres"
          - name: POSTGRESQL_PGAUDIT_LOG
            value: "READ"
          - name: POSTGRESQL_LOG_HOSTNAME
            value: "true"
          - name: POSTGRESQL_REPLICATION_MODE
            value: "slave"
          - name: POSTGRESQL_REPLICATION_USER
            value: "repl_user"
          - name: POSTGRESQL_REPLICATION_PASSWORD
            value: "repl_user"
          - name: POSTGRESQL_MASTER_PORT_NUMBER
            value: "5432"
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-slave-pvc-02
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-slave-pv-02
  namespace: postgres-02
  labels:
    type: local
    app: postgres-slave-02
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /nfs/data/pg-sql-02/master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-slave-pvc-02
  namespace: postgres-02
  labels:
    app: postgres-slave-02
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-slave-svc-02
  namespace: postgres-02
  labels:
    app: postgres-slave-02
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres-slave-02